### PR TITLE
Provide Dockerfile to build the oslat container image

### PR DESCRIPTION
**Pull request by cynepco3hahue**
Signed-off-by: Artyom Lukianov <alukiano@redhat.com>

### CODE REVIEW

**Comment by xzpeter** [comment]
Hi, Artyom,

Firstly, thanks for the patch!

I have two small questions.  Since I'm not very familiar with the container world, the questions can be naive, please bear with me. :)

(1) I got this error when building the docker image:

Errors during downloading metadata for repository 'AppStream':
  - Curl error (6): Couldn't resolve host name for http://mirrorlist.centos.org/?release=8&arch=x86_64&repo=AppStream&infra=container [Could not resolve host:
 mirrorlist.centos.org]                                                        
Error: Failed to download metadata for repo 'AppStream': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for http://mirrorlist.
centos.org/?release=8&arch=x86_64&repo=AppStream&infra=container [Could not resolve host: mirrorlist.centos.org]

However http://mirrorlist.centos.org/ is definitely resolvable on my host itself.  Do you know why?

(2) Since oslat should be a public repository for everyone, shall we avoid using explicit sites in the makefile?  E.g., "quay.io", or "openshift-kni"?

Thanks,

**Comment by xzpeter** [comment]
Appending another question: (3) Is there a simple way to append extra parameters to the last "CMD ["/usr/bin/oslat"]" in the docker file when initiating a docker container based on the image?  Asked since in most cases oslat should not be run with the default parameters, so I'm thinking whether we should just let the container user to trigger the command instead.

**Comment by cynepco3hahue** [comment]
> Hi, Artyom,
> 
> Firstly, thanks for the patch!
> 
> I have two small questions. Since I'm not very familiar with the container world, the questions can be naive, please bear with me. :)
> 
> (1) I got this error when building the docker image:
> 
> Errors during downloading metadata for repository 'AppStream':
> 
> * Curl error (6): Couldn't resolve host name for http://mirrorlist.centos.org/?release=8&arch=x86_64&repo=AppStream&infra=container [Could not resolve host:
>   mirrorlist.centos.org]
>   Error: Failed to download metadata for repo 'AppStream': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for http://mirrorlist.
>   centos.org/?release=8&arch=x86_64&repo=AppStream&infra=container [Could not resolve host: mirrorlist.centos.org]
> 
> However http://mirrorlist.centos.org/ is definitely resolvable on my host itself. Do you know why?
> 

I know that sometime the CentOS can return this kind of errors, when it has a load on the server, can you please try again and give me know if you still have the same problem.

> (2) Since oslat should be a public repository for everyone, shall we avoid using explicit sites in the makefile? E.g., "quay.io", or "openshift-kni"?

In general, the quay is available for everyone the same as openshift-kni(everyone can take a look inside of it), similar to the docker.io, but I do not have a strong opinion here, so if you have better default values I will just use them :)
> 
> Thanks,



> Appending another question: (3) Is there a simple way to append extra parameters to the last "CMD ["/usr/bin/oslat"]" in the docker file when initiating a docker container based on the image? Asked since in most cases oslat should not be run with the default parameters, so I'm thinking whether we should just let the container user to trigger the command instead.

You can run it this way `docker run -d --privileged ff6cdd945c54 oslat -c 2,3 -C 1 -t 180` and append any arguments you want.

**Comment by xzpeter** [comment]
> I know that sometime the CentOS can return this kind of errors, when it has a load on the server, can you please try again and give me know if you still have the same problem.

It still happens. However I switched to another host with podman, issue gone.  Probably something wrong with my configuration on the first host. :-/

> 
> > (2) Since oslat should be a public repository for everyone, shall we avoid using explicit sites in the makefile? E.g., "quay.io", or "openshift-kni"?
> 
> In general, the quay is available for everyone the same as openshift-kni(everyone can take a look inside of it), similar to the docker.io, but I do not have a strong opinion here, so if you have better default values I will just use them :)

The problem is that if with that "make push-container" will fail by default for mostly everyone because of a strange lacking permission error that no one will be able to fix.  I am fine with keeping IMAGE_REGISTRY's default value as "guay.io", however I prefer to at least not hard-code REGISTRY_NAMESPACE to some specific account.  If the entry is required, let's fail gracefully when "make" triggers with explicit errors, e.g., "Please specify REGISTRY_NAMESPACE first".  Does it make sense to you?

> 
> > Thanks,
> 
> > Appending another question: (3) Is there a simple way to append extra parameters to the last "CMD ["/usr/bin/oslat"]" in the docker file when initiating a docker container based on the image? Asked since in most cases oslat should not be run with the default parameters, so I'm thinking whether we should just let the container user to trigger the command instead.
> 
> You can run it this way `docker run -d --privileged ff6cdd945c54 oslat -c 2,3 -C 1 -t 180` and append any arguments you want.

I see, thanks.  Then does it also mean that the last "CMD" line can be removed from the Dockerfile?

I have another question on the "--no-cache" btw:  Due to the multi-stage build, it'll create one anonymous image for each "make build-container" so disk space is easily filled up.  Can we remove that, or is there a reason?

**Comment by cynepco3hahue** [comment]
> The problem is that if with that "make push-container" will fail by default for mostly everyone because of a strange lacking permission error that no one will be able to fix. I am fine with keeping IMAGE_REGISTRY's default value as "guay.io", however I prefer to at least not hard-code REGISTRY_NAMESPACE to some specific account. If the entry is required, let's fail gracefully when "make" triggers with explicit errors, e.g., "Please specify REGISTRY_NAMESPACE first". Does it make sense to you?

Yes, I will set an empty ENV variable and will add the check.



> I see, thanks. Then does it also mean that the last "CMD" line can be removed from the Dockerfile?

Will remove it, I can set it to the ENTRYPOINT, but it less comfortable for debugging, because you will need to override it each time you will want to use bash.

> 
> I have another question on the "--no-cache" btw: Due to the multi-stage build, it'll create one anonymous image for each "make build-container" so disk space is easily filled up. Can we remove that, or is there a reason?

The only reason, it always to get last updated dependencies on the build, because quay, for example, has a vulnerability scanner that gives a score to the image according to all CVEs. But if you prefer I can remove the no-cache option.

**Comment by cynepco3hahue** [comment]
I have some question regarding running the `oslat`, I run the `oslat` command on the VM with 8 cores(I am just checking that it works, not the real performance):
```
oslat --runtime 600 --rtprio 1 --cpu-list 2,3,4,5 --cpu-main-thread 1
```
when my container pinned to the CPUs 1-5, so I have 3 additional CPUs, but the machine is totally frozen until the command finish. I can see this behavior only with the `--rtprio 1` parameter, does it expected behavior because I was sure it should not affect other CPUs except specified.

**Comment by xzpeter** [comment]
> > I have another question on the "--no-cache" btw: Due to the multi-stage build, it'll create one anonymous image for each "make build-container" so disk space is easily filled up. Can we remove that, or is there a reason?
> 
> The only reason, it always to get last updated dependencies on the build, because quay, for example, has a vulnerability scanner that gives a score to the image according to all CVEs. But if you prefer I can remove the no-cache option.

Just want to make sure no endless disk consumption.  Removing it would work, or we can manually delete the anonymous image every time after the build (as long as there is a way to identify which image to delete) would work too.

> I have some question regarding running the `oslat`, I run the `oslat` command on the VM with 8 cores(I am just checking that it works, not the real performance):
> 
> ```
> oslat --runtime 600 --rtprio 1 --cpu-list 2,3,4,5 --cpu-main-thread 1
> ```
> 
> when my container pinned to the CPUs 1-5, so I have 3 additional CPUs, but the machine is totally frozen until the command finish. I can see this behavior only with the `--rtprio 1` parameter, does it expected behavior because I was sure it should not affect other CPUs except specified.

It's easy to hang a RT system, e.g., when the bash process want to do a synchronous operation across all cores while the sync task cannot be scheduled on time when the RT thread is running on some cores with higher priority than the sync task/thread.  From that pov, oslat can be seen as a simplest busy loop program (e.g. "while (1);").  I'll see whether I can reproduce this too.

**Comment by xzpeter** [comment]
> Just want to make sure no endless disk consumption. Removing it would work, or we can manually delete the anonymous image every time after the build (as long as there is a way to identify which image to delete) would work too.

When I said "manually" I meant in the makefile. :)

**Comment by cynepco3hahue** [comment]
@xzpeter I fixed all comment, can you please review again?

**Comment by xzpeter** [comment]
Looks good, thanks!

**Comment by cynepco3hahue** [comment]
Thanks for the review!

**Pull request merged**
